In [21]:
import pandas as pd
import numpy as np

if __name__ == "__main__":
    #  Load training data
    data_train = pd.read_csv("../data/Iris_train.csv")
    # Separate independent variables and dependent variables
    independent = ["SepalLengthCm",	"SepalWidthCm",	"PetalLengthCm",	"PetalWidthCm"]
    X = data_train[independent]
    y = data_train["Species"]
    def dist(a, b):
            # Compute Euclidean distance between a and b
            return np.sum((np.array(a)-np.array(b))**2)**(0.5)
    
    n_clusters = 8
    cluster_centers = []
    w = np.array([1/len(X)]*len(X))
    min_square_d = np.array(0 * n_clusters)
    X = X.to_numpy()

    sample = np.random.choice(len(X), n_clusters, p=w)
    cluster_centers = X[sample]
    print(cluster_centers)

[[6.  2.9 4.5 1.5]
 [5.4 3.4 1.7 0.2]
 [5.7 3.  4.2 1.2]
 [5.6 2.7 4.2 1.3]
 [6.5 3.2 5.1 2. ]
 [5.1 3.3 1.7 0.5]
 [7.6 3.  6.6 2.1]
 [6.1 3.  4.9 1.8]]


In [7]:
import numpy as np
import random

a = [1,2,3,4,5]

for i in range(15):
    print("Iteration:", i, "Random choice is ")
    randomItem = np.random.choice(5, 1, (.11, .1, .3, .5, .1))
    print(randomItem)

numberList = ["Kelly", "Scott", "Emma", "Jon"]
for i in range(5):
    print("Iteration:", i, "Random choice is ")
    randomItem = np.random.choice(numberList, cum_weights=(5, 15, 30, 50), k=1)
    print(randomItem[0])

Iteration: 0 Random choice is 
[0]
Iteration: 1 Random choice is 
[0]
Iteration: 2 Random choice is 
[2]
Iteration: 3 Random choice is 
[3]
Iteration: 4 Random choice is 
[0]
Iteration: 5 Random choice is 
[0]
Iteration: 6 Random choice is 
[1]
Iteration: 7 Random choice is 
[0]
Iteration: 8 Random choice is 
[0]
Iteration: 9 Random choice is 
[4]
Iteration: 10 Random choice is 
[1]
Iteration: 11 Random choice is 
[3]
Iteration: 12 Random choice is 
[3]
Iteration: 13 Random choice is 
[4]
Iteration: 14 Random choice is 
[3]
Iteration: 0 Random choice is 


TypeError: choice() got an unexpected keyword argument 'cum_weights'

In [35]:
import numpy as np

w = np.array(1*3)
cluster = [1,2,3]
w = cluster /2.0

print(cluster)
clusters = [[] for i in range(3)]
clusters[1].append([3.5,3.2])
clusters[1].append([3.1,3.1])
clusters[0].append(3.3)
clusters[2].append(3.3)
clusters[0] = 1
print(len(clusters))

# for x in clusters:
#     for y in x:
#         print(y)

TypeError: unsupported operand type(s) for /: 'list' and 'float'

In [14]:
a = [1,2]
a**2
a

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'